order: '01'
dark: false
title_en: Bride Production
title_pt: Produção de Noiva
title_sp: Producción de Novia
desc_en: >-
  Complete bridal styling tailored to your vision. With over 2,000 brides
  served, we create unforgettable looks in salons, beaches, hotels, castles,
  and destinations of your choice.
desc_pt: >-
  Penteados nupciais completos adaptados à sua visão. Com mais de 2.000 noivas
  atendidas, criamos looks inesquecíveis em salões, praias, hotéis, castelos e
  destinos de sua escolha.
desc_sp: >-
  Estilismo nupcial completo adaptado a tu visión. Con más de 2.000 novias
  atendidas, creamos looks inolvidables en salones, playas, hoteles, castillos y
  destinos de tu elección.
